# ===============================
# APPLICATION
# ===============================

spring.application.name=interview-iq-progress-service


# ===============================
# SERVER
# ===============================

# Render provides PORT automatically.
# Locally Spring will run on port 8081.
server.port=${PORT:8081}


# ===============================
# ERROR CONFIGURATION
# ===============================

server.error.include-message=always
server.error.include-binding-errors=always
